# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 285ba970d4f16989e8af4f81e4112986d3b73b09d31a1f3d0a7a58e917b9ec8e5811ea0e9188e8b6a20ec8a15c8e905dd4ca62354f8e11af6b4692ce5897168d

test:
  secret_key_base: 4947128273b3d663cd93841cdb6889c4584e7a329c7f73a3f9ec27fe3fdc1c9a914c23435e15f174a54aea76bad0dab8328fc901366880b1388ef0121a8721eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
